SELECT C.CAR_ID, C.CAR_TYPE, 
    (CASE P.DURATION_TYPE
        WHEN NULL THEN C.DAILY_FEE * 30
        ELSE CAST(C.DAILY_FEE * 30 * (1 - DISCOUNT_RATE/100) AS SIGNED)
    END) FEE
FROM CAR_RENTAL_COMPANY_CAR C
JOIN (
    SELECT CAR_ID, MIN(START_DATE) START_DATE, MAX(END_DATE) END_DATE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    GROUP BY CAR_ID) H ON H.CAR_ID = C.CAR_ID
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON P.CAR_TYPE = C.CAR_TYPE
WHERE C.CAR_TYPE IN ('세단', 'SUV') 
    AND (H.START_DATE > '2022-11-30' OR H.END_DATE < '2022-11-01' )
    AND ((P.DURATION_TYPE IS NULL 
            AND 500000 <= C.DAILY_FEE * 30 AND C.DAILY_FEE * 30 < 2000000
         )
         OR (P.DURATION_TYPE = '30일 이상' 
             AND (500000 <= C.DAILY_FEE * 30 * (1 - DISCOUNT_RATE/100) 
                  AND C.DAILY_FEE * 30 * (1 - DISCOUNT_RATE/100) < 2000000)))
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC;