-- 코드를 입력하세요

SELECT YEAR(OS.SALES_DATE) YEAR, MONTH(OS.SALES_DATE) MONTH,
    COUNT(DISTINCT(OS.USER_ID)) PUCHASED_USERS,
    ROUND(
        COUNT(DISTINCT(OS.USER_ID))/(
            SELECT COUNT(USER_ID) FROM USER_INFO WHERE JOINED LIKE ('2021%')
        ), 1) PUCHASED_RATIO
FROM (
    SELECT USER_ID FROM USER_INFO WHERE JOINED LIKE ('2021%')
) U
INNER JOIN ONLINE_SALE OS ON U.USER_ID = OS.USER_ID
GROUP BY YEAR(OS.SALES_DATE), MONTH(OS.SALES_DATE)
ORDER BY YEAR(OS.SALES_DATE), MONTH(OS.SALES_DATE);